// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8WAgxmHPLENcjJCMA1lTlseTuJtearrw',
    appId: '1:122811678591:web:9912489a5d23d8b867a44a',
    messagingSenderId: '122811678591',
    projectId: 'flutter-reddit-clone-59aeb',
    authDomain: 'flutter-reddit-clone-59aeb.firebaseapp.com',
    storageBucket: 'flutter-reddit-clone-59aeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACsp5BccnA-hPOMJ4ZqXZ17-PZ_ft5B6w',
    appId: '1:122811678591:android:65727cda2b8ef37d67a44a',
    messagingSenderId: '122811678591',
    projectId: 'flutter-reddit-clone-59aeb',
    storageBucket: 'flutter-reddit-clone-59aeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmwlZmKp40tH7DprDpCrT1CtMR77pQSkA',
    appId: '1:122811678591:ios:ea788b0d04ae9e7c67a44a',
    messagingSenderId: '122811678591',
    projectId: 'flutter-reddit-clone-59aeb',
    storageBucket: 'flutter-reddit-clone-59aeb.appspot.com',
    iosClientId: '122811678591-58pt74esogbcliiac7enlsc4fq612a43.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
